This notebook will demonstrate how to use the **constrained training algorithms** implemented in this toolkit.

To train a network, instantiate an algorithm, passing to it the model, the dataset, a list of `FairnessConstraint`s and the algorithm's hyperparameters.

Load and prepare data from `folktables`:

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
from folktables import ACSDataSource, ACSIncome

# load folktables data
data_source = ACSDataSource(survey_year='2018', horizon='1-Year', survey='person')
acs_data = data_source.get_data(states=["OK"], download=True)
features, labels, groups = ACSIncome.df_to_numpy(acs_data)
# split
X_train, X_test, y_train, y_test, groups_train, groups_test = train_test_split(
    features, labels, groups, test_size=0.2, random_state=42)
# scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# make into a pytorch dataset, remove the sensitive attribute (RAC1P)
features_train = torch.tensor(X_train, dtype=torch.float32)[:,:-1]
labels_train = torch.tensor(y_train,dtype=torch.float32)
dataset_train = torch.utils.data.TensorDataset(features_train, labels_train)

c_batch_size = 32
min_subgroup_size = 32
# For each subgroup, FairnessConstraint needs a list of indices of samples belonging to that subgroup
group_indices_train = [
    np.nonzero(groups_train == group_id)[0] for group_id in np.unique(groups_train)
    if np.count_nonzero(groups == group_id) > min_subgroup_size
]

# repeat for test set
features_test = torch.tensor(X_test, dtype=torch.float32)[:,:-1]
labels_test = torch.tensor(y_test,dtype=torch.float32)
dataset_test = torch.utils.data.TensorDataset(features_test, labels_test)
group_indices_test = [
    np.nonzero(groups_test == group_id)[0] for group_id in np.unique(groups_test)
    if np.count_nonzero(groups == group_id) > min_subgroup_size
]

print(f'Protected attribute: {ACSIncome.group}')
print(f'Number of subgroups considered: {len(group_indices_train)}')
print(f'Size of subgroups: {[len(g) for g in group_indices_train]}')

Protected attribute: RAC1P
Number of subgroups considered: 7
Size of subgroups: [10685, 794, 1213, 59, 259, 315, 997]


Let's say we want to add an equal loss constraint on the model.

We can do that by using the `FairnessConstraint` class, which will handle sampling (if possible, sampling an equal number of samples from each relevant subgroup in each minibatch), and passing it the function that will calculate the value of the constraint.

In [ ]:
from itertools import combinations
from src.constraints.constraint import FairnessConstraint
from src.constraints.constraint_fns import loss_equality

# the protected attribute is "Race" (RAC1P)
# we put a pairwise constraint on each combination of subgroups
constraint_bound = 0.05
constraints = []
for gr1, gr2 in combinations(group_indices_train, 2):
    c = FairnessConstraint(
        dataset=dataset_train,
        group_indices=[gr1, gr2],
        # subtract bound from absolute loss difference to bring constraint to form $c \leq 0$
        fn=lambda model, samples: torch.abs(loss_equality(torch.nn.BCEWithLogitsLoss(), model, samples)) - constraint_bound,
        batch_size=c_batch_size,
        seed=0
    )

    constraints.append(c)

print(f'Number of constraints: {len(constraints)}')

Number of constraints: 21


In [ ]:
# helper function to analyze model performance

def model_stats(model, features, labels, groups):
    with torch.inference_mode():
        gr_ind = list(combinations(groups, 2))
        vals = []
        acc_dif = []
        for i, c in enumerate(constraints[::2]):
            idx1, idx2 = gr_ind[i]
            val = c.eval(model, [(features[idx1], labels[idx1]), (features[idx2], labels[idx2])]) + constraint_bound
            vals.append(abs(val.numpy().item()))

            logits1 = model(features[idx1])
            logits2 = model(features[idx2])
            outs1 = torch.nn.functional.sigmoid(logits1).numpy()
            outs2 = torch.nn.functional.sigmoid(logits2).numpy()
            preds1 = (outs1.T > 0.5).astype(float)
            preds2 = (outs2.T > 0.5).astype(float) 
            acc1 = np.mean(preds1 == labels[idx1].numpy())
            acc2 = np.mean(preds2 == labels[idx2].numpy())
            acc_dif.append(abs(acc1-acc2))

        print(f'constraints (should be <= {constraint_bound}):')
        print(np.round(vals, decimals=3))
        print(f'c mean: {np.mean(vals)}')
        print(f'c min: {np.min(vals)}')
        print(f'c max: {np.max(vals)}')
        print('---')

        logits = model(features)
        outs = torch.nn.functional.sigmoid(logits).numpy()
        preds = (outs.T > 0.5).astype(float)
        acc = np.sum(preds == labels.numpy())/len(labels)
        print(f'accuracy: {acc}')
        print('accuracy abs. difference:')
        print(np.round(acc_dif, decimals=3))
        print(f'acc abs dif mean: {np.mean(acc_dif)}')
        print(f'acc abs dif min: {np.min(acc_dif)}')
        print(f'acc abs dif max: {np.max(acc_dif)}')

---
---

For comparison, let us first train a model **without constraints**.

Define a model:

In [ ]:
from torch.nn import Sequential
hsize1 = 64
hsize2 = 32
model_uncon = Sequential(
    torch.nn.Linear(features_train.shape[1], hsize1),
    torch.nn.ReLU(),
    torch.nn.Linear(hsize1, hsize2),
    torch.nn.ReLU(),
    torch.nn.Linear(hsize2, 1)
)

And start training:

In [ ]:
from torch.optim import Adam

loader = torch.utils.data.DataLoader(dataset_train, batch_size=32, shuffle=True)
loss = torch.nn.BCEWithLogitsLoss()
optimizer = Adam(model_uncon.parameters())
epochs = 50

for epoch in range(epochs):
    losses = []
    for batch_feat, batch_label in loader:
        optimizer.zero_grad()

        logit = model_uncon(batch_feat)
        loss = torch.nn.functional.binary_cross_entropy_with_logits(logit.squeeze(), batch_label)
        loss.backward()

        optimizer.step()
        losses.append(loss.item())
    print(f"Epoch: {epoch}, loss: {np.mean(losses)}")

Epoch: 0, loss: 0.4567770318327738
Epoch: 1, loss: 0.4267354179506323
Epoch: 2, loss: 0.42177021729626823
Epoch: 3, loss: 0.41923434915952384
Epoch: 4, loss: 0.4167473852368338
Epoch: 5, loss: 0.4148108066791402
Epoch: 6, loss: 0.41341322707012296
Epoch: 7, loss: 0.4125295749399811
Epoch: 8, loss: 0.4119187536915498
Epoch: 9, loss: 0.41052870083201143
Epoch: 10, loss: 0.4095372299530676
Epoch: 11, loss: 0.4085638278962246
Epoch: 12, loss: 0.40801226420860204
Epoch: 13, loss: 0.4076137725662972
Epoch: 14, loss: 0.4061356251061495
Epoch: 15, loss: 0.40524284524976145
Epoch: 16, loss: 0.4051640779445214
Epoch: 17, loss: 0.4038818087761423
Epoch: 18, loss: 0.40338663783456596
Epoch: 19, loss: 0.40176192541340633
Epoch: 20, loss: 0.4007976305271898
Epoch: 21, loss: 0.40091671312360894
Epoch: 22, loss: 0.40019975090399384
Epoch: 23, loss: 0.3993254276325128
Epoch: 24, loss: 0.3990602514240891
Epoch: 25, loss: 0.39761721761897206
Epoch: 26, loss: 0.3975723823865077
Epoch: 27, loss: 0.39697754

Let's now analyze how well the **unconstrained** model does in terms of constraints:

In [ ]:
print('TRAIN')
model_stats(model_uncon, features_train, labels_train, group_indices_train)

TRAIN
constraints (should be <= 0.05):
[0.09  0.011 0.041 0.049 0.168 0.058 0.079 0.131 0.041 0.078 0.032]
c mean: 0.07068421894853766
c min: 0.01083877682685852
c max: 0.16823594272136688
---
accuracy: 0.815530593734738
accuracy abs. difference:
[0.055 0.007 0.01  0.039 0.098 0.034 0.048 0.065 0.016 0.043 0.021]
acc abs dif mean: 0.03959708931426114
acc abs dif min: 0.007040249118406505
acc abs dif max: 0.09811707556209193


In [ ]:
print('TEST')
model_stats(model_uncon, features_test, labels_test, group_indices_test)

TEST
constraints (should be <= 0.05):
[0.037 0.064 0.401 0.064 0.034 0.084 0.101 0.438 0.102 0.004 0.047]
c mean: 0.12501090223138983
c min: 0.003509730100631714
c max: 0.43779516220092773
---
accuracy: 0.79296875
accuracy abs. difference:
[0.038 0.056 0.125 0.029 0.047 0.049 0.094 0.164 0.068 0.009 0.011]
acc abs dif mean: 0.06271492998802909
acc abs dif min: 0.008671103044968764
acc abs dif max: 0.16374269005847952


---
---

Now let us train the same model with one of the **constrained** training algorithms:

In [ ]:
from src.algorithms import SSLALM
from torch.nn import Sequential

hsize1 = 64
hsize2 = 32
model = Sequential(
    torch.nn.Linear(features_train.shape[1], hsize1),
    torch.nn.ReLU(),
    torch.nn.Linear(hsize1, hsize2),
    torch.nn.ReLU(),
    torch.nn.Linear(hsize2, 1)
)

optimizer = SSLALM(
    net=model,
    data=dataset_train,
    loss=torch.nn.BCEWithLogitsLoss(),
    constraints=constraints,
)

history = optimizer.optimize(max_runtime=180,batch_size=32,seed=42)

In [ ]:
print('TRAIN')
model_stats(model, features_train, labels_train, group_indices_train)

TRAIN
constraints (should be <= 0.05):
[0.032 0.017 0.001 0.02  0.033 0.035 0.015 0.034 0.013 0.001 0.003]
c mean: 0.018650136210701683
c min: 0.0010441243648529053
c max: 0.035471320152282715
---
accuracy: 0.7885997348775553
accuracy abs. difference:
[0.071 0.023 0.004 0.074 0.113 0.045 0.048 0.067 0.003 0.043 0.026]
acc abs dif mean: 0.04679565636107975
acc abs dif min: 0.0030732423679527
acc abs dif max: 0.11312847709665674


In [ ]:
print('TEST')
model_stats(model, features_test, labels_test, group_indices_test)

TEST
constraints (should be <= 0.05):
[0.016 0.027 0.082 0.052 0.017 0.047 0.042 0.097 0.068 0.001 0.031]
c mean: 0.04356678507544778
c min: 0.0011366009712219238
c max: 0.09749960899353027
---
accuracy: 0.7876674107142857
accuracy abs. difference:
[0.084 0.026 0.052 0.053 0.069 0.045 0.11  0.032 0.137 0.015 0.039]
acc abs dif mean: 0.06007948193801135
acc abs dif min: 0.014922363379713643
acc abs dif max: 0.13668351670135792
